### ISSUE TITLE
spawn jscodeshift ENOENT

### ISSUE THREAD

**Issue by 990094523** [lucasbento/rn-update-deprecated-modules#3]
my english is poor
it does not work, 

![1](https://user-images.githubusercontent.com/27407218/56791959-07849780-683b-11e9-9cca-af47bf66c5fe.png)

![2](https://user-images.githubusercontent.com/27407218/56792328-f2f4cf00-683b-11e9-8a4e-590b3e0fb6d2.png)

**Comment by lucasbento** [comment]
Hi @990094523, can you run `npx --version` and put the output here?

**Comment by 990094523** [comment]
![1](https://user-images.githubusercontent.com/27407218/57203083-51117700-6fdf-11e9-8129-7045093a37cb.png)

**Comment by lucasbento** [comment]
@990094523: can you try installing it globally and running it then?

I did not notice at first that you were using Windows, I haven't tested on it.

Please run `npm install rn-update-deprecated-modules --global` and then `rn-update-deprecated-modules`.

**Comment by 990094523** [comment]
It looks like the same problem.
![12](https://user-images.githubusercontent.com/27407218/57216692-2ba65c80-7023-11e9-824c-d19f1b64c8fe.png)

**Comment by lucasbento** [comment]
@990094523: would you please be able to try #4? I just tested on Windows and it seems to work fine.

**Comment by lucasbento** [comment]
@990094523L: nice, good to hear!

I'll just run a few more tests on #4 and then will release it.

**Comment by lucasbento** [comment]
@990094523: published [`0.59.1`](https://github.com/lucasbento/rn-update-deprecated-modules/releases/tag/v0.59.1).

Thanks for reporting this!
